# Generated by Django 5.2.3 on 2025-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Librarian', 'Librarian'), ('Member', 'Member')], default='Member', help_text='User role that determines access permissions', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter your date of birth', null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo (optional)', null=True, upload_to='profile_photos/', verbose_name='profile photo'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
